### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by DiputsMonro** [navingator/resume-website#1]
Your **Northwind Demo Application** section fails to credit me for having the revolutionary idea to put emjoi in menu items.  I expect remediation and remuneration forthwith!

**Comment by DiputsMonro** [comment]
This is my way of saying "neat website!"

**Comment by navingator** [comment]
You shall henceforth have 1% of all future profits of that extraordinarily profitable website as remuneration. 
And an extra 1% for the compliment. 💰
